. ~/git/vanilla/postgres/pg_config.sh
psql <<EOF
DROP TABLE accounts;
DROP TABLE accounts_scaled;
CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_name VARCHAR(200) NOT NULL,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('ASSET', 'LIABILITY', 'CAPITAL', 'INCOME', 'EXPENSE')),
    currency_code VARCHAR(3) NOT NULL,
    opening_balance DECIMAL(23,2) DEFAULT 0,
    current_balance DECIMAL(23,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE accounts_scaled as TABLE accounts;

-- drop UNIQUE CONSTRAINT because of not implemented checks for uniqueness
ALTER TABLE accounts DROP CONSTRAINT accounts_account_number_key;
EOF

java -Xmx2G -Xms2G -jar target/postgres-table-scaler-1.0.0-all.jar --host $PGHOST --port $PGPORT --db postgres --user $PGUSER --pool-size 100 -i accounts -g -n 10000 -t 100 -b 1000 -s 100 -o accounts_scaled
